git:
  commit: true
  commitMessage: "build: release v${version}"
  requireCleanWorkingDir: true
  tagAnnotation: ""
  tagName: v${version}
github:
  release: true
  releaseName: Release ${version}
npm:
  publish: false
hooks:
  before:git:beforeRelease:
    - pnpm format
plugins:
  "@release-it/conventional-changelog":
    preset: angular
    infile: CHANGELOG.md
