version: "3.7"

#
# [ services ]
#
services:
  nginx:
    build:
      context: ./docker/nginx
      args:
        - version=1.17.8
    ports:
      - "80:80"
      - "443:443"
    networks:
      frontend:
    volumes:
      - type: bind
        consistency: cached
        source: ./public
        target: /var/www
      - type: bind
        source: ./docker/nginx/certs/
        target: /etc/nginx/ssl/
      - type: bind
        source: ./docker/nginx/components/
        target: /etc/nginx/components/
      - type: bind
        source: ./docker/nginx/conf.d/
        target: /etc/nginx/conf.d/

#
# [ networks ]
#
networks:
  frontend:
