name: Build website

on:
  pull_request:

jobs:
  build:
    name: Build Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install --frozen-lockfile --silent --ignore-engines --non-interactive --production
      - run: yarn run build
        env:
          CI: true
    # TODO: run on Windows
    # TODO: run on macOS
