name: Default

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Lint styles
        run: pnpm stylelint '**/*.{scss,vue}'
      - name: Lint scripts
        run: pnpm eslint '**/*.{js,ts,vue}'
      - name: Lint types
        run: pnpm vue-tsc --noEmit

  build:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: "pnpm"
      - name: Install & build
        run: |
          pnpm install
          pnpm vite build -m development --sourcemap
      - uses: actions/upload-artifact@v3
        with:
          name: www
          path: dist/
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: preview

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: www
      - name: Vercel
        uses: amondnet/vercel-action@v20.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          # alias-domains: |
          #   ${{ branch }}.muuvmuuv.vercel.app
          #   pr-${{ pr }}.muuvmuuv.vercel.app
