# https://github.com/dawidd6/action-send-mail

name: Fork created

on:
  fork:

jobs:
  notify_email:
    name: Notify by email
    runs-on: ubuntu-latest

    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          format: markdown
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            The user `<user>` forked the repository just now

            ${{ github.ref }}
