name: Lint files

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install --frozen-lockfile --silent --ignore-engines --non-interactive --production=false
      - run: yarn run lint:js-source
      - run: yarn run lint:js-engine
      - run: yarn run lint:scss
