# https://github.com/appleboy/telegram-action

name: New Release

on:
  release:
    types:
      - published

jobs:
  new_release:
    name: New release
    runs-on: ubuntu-latest

    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          format: markdown
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            A _new version_ has been publised. (**v${{ github.ref }}**)

            View it now on: [https://marvin.digital/](https://marvin.digital/?force_reload=true)
